name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/<organization>/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.DOMAIN_DESIGN_NUGET_API_KEY }}       

      - name: Build solution and generate NuGet package
        run: |  
          cd Domain.Design.Foundations
          dotnet pack -c Release -o out  

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./Domain.Design.Foundations/out/*.nupkg --skip-duplicate --no-symbols true
