name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update NuGet package
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-dotnet@v1    
        with:
            dotnet-version: '3.1.100'
      - run: dotnet pack -c Release -o out  
      - run: ls
      - run: dotnet nuget push ./out/*.nupkg -k ${{ secrets.DOMAIN_DESIGN_NUGET_API_KEY }} --skip-duplicate --no-symbols true -s https://api.nuget.org/v3/index.json
