name: gated

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
  pull_request_review:
    types: [submitted, edited]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Gated Pull Request Build
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Install .NET Core v3.1.100
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100'

      - name: Run tests
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov

      - name: Publish coverage report to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}