name: release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update NuGet package
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      
      - name: Install .NET Core v3.1.100
        uses: actions/setup-dotnet@v1    
        with:
            dotnet-version: '3.1.100'
            
      - name: Install MSBuild Coverlet
        run: dotnet add Tests.Foundations package coverlet.msbuild
      
      - name: Build nuget release package
        run: dotnet pack -c Release -o out  

      - name: Generate coverage report
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutput=../coverage/lcov.info /p:CoverletOutputFormat=lcov /p:MergeWith=../coverage/.lcov.info
      
      - name: Publish coverage report to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
      
      - name: Publish Domain.Design.Foundations
        run: dotnet nuget push ./out/Domain.Design.Foundations.*.nupkg -k ${{ secrets.NUGET_GALLERY_API_KEY }} --skip-duplicate --no-symbols true -s https://api.nuget.org/v3/index.json
        
      - name: Publish Domain.Design.Foundations.Extensions.DependencyInjection
        run: dotnet nuget push ./out/Domain.Design.Foundations.Extensions.DependencyInjection.*.nupkg -k ${{ secrets.NUGET_GALLERY_API_KEY }} --skip-duplicate --no-symbols true -s https://api.nuget.org/v3/index.json
          
      - name: Publish Domain.Design.Foundations.Extensions.DependencyInjection.MediatR
        run: dotnet nuget push ./out/Domain.Design.Foundations.Extensions.DependencyInjection.MediatR.*.nupkg -k ${{ secrets.NUGET_GALLERY_API_KEY }} --skip-duplicate --no-symbols true -s https://api.nuget.org/v3/index.json  
        